<div id="site_logo">
<img src="http://www.voyacode.com/images/logo_text.png" alt="Site logo">
</div>
<nav>
	<ul>
		<li><a href="http://www.voyacode.com/index.php"><div>Home</div></a>
		<li><a href="http://www.voyacode.com/blogs"><div>Blogs</div></a>
		<li><a href="http://www.voyacode.com/projects"><div>Projects</div></a>
		<li><a href="http://www.voyacode.com/projects/other_projects.php"><div>Other projects</div></a>
		<li><a href="http://www.voyacode.com/comments"><div>Comments</div></a>
	</ul>
</nav>